//
// AllStoresAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AllStoresAPI {

    /**

     - returns: [Store]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func storesGet() async throws -> [Store] {
        return try await storesGetWithRequestBuilder().execute().body
    }

    /**
     - GET /stores
     - returns: RequestBuilder<[Store]> 
     */
    open class func storesGetWithRequestBuilder() -> RequestBuilder<[Store]> {
        let localVariablePath = "/stores"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Store]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()
//        print(localVariableUrlComponents?.string ?? localVariableURLString)
        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
