//
// RMCharactersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RMCharactersAPI {

    /**

     - parameter page: (query)  (optional)
     - parameter id: (query) The id of the character (optional)
     - parameter name: (query) The name of the character. (optional)
     - parameter status: (query) The status of the character (&#39;Alive&#39;, &#39;Dead&#39; or &#39;unknown&#39;). (optional)
     - parameter species: (query) The species of the character. (optional)
     - parameter type: (query) The type or subspecies of the character. (optional)
     - parameter gender: (query) The gender of the character (&#39;Female&#39;, &#39;Male&#39;, &#39;Genderless&#39; or &#39;unknown&#39;). (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func characterGet(page: Double? = nil, id: Double? = nil, name: String? = nil, status: String? = nil, species: String? = nil, type: String? = nil, gender: String? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: RMHeroesList?, _ error: Error?) -> Void)) -> RequestTask {
        return characterGetWithRequestBuilder(page: page, id: id, name: name, status: status, species: species, type: type, gender: gender).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /character
     - parameter page: (query)  (optional)
     - parameter id: (query) The id of the character (optional)
     - parameter name: (query) The name of the character. (optional)
     - parameter status: (query) The status of the character (&#39;Alive&#39;, &#39;Dead&#39; or &#39;unknown&#39;). (optional)
     - parameter species: (query) The species of the character. (optional)
     - parameter type: (query) The type or subspecies of the character. (optional)
     - parameter gender: (query) The gender of the character (&#39;Female&#39;, &#39;Male&#39;, &#39;Genderless&#39; or &#39;unknown&#39;). (optional)
     - returns: RequestBuilder<RMHeroesList> 
     */
    open class func characterGetWithRequestBuilder(page: Double? = nil, id: Double? = nil, name: String? = nil, status: String? = nil, species: String? = nil, type: String? = nil, gender: String? = nil) -> RequestBuilder<RMHeroesList> {
        let localVariablePath = "/character"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "id": (wrappedValue: id?.encodeToJSON(), isExplode: true),
            "name": (wrappedValue: name?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
            "species": (wrappedValue: species?.encodeToJSON(), isExplode: true),
            "type": (wrappedValue: type?.encodeToJSON(), isExplode: true),
            "gender": (wrappedValue: gender?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RMHeroesList>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
