//
// Cat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Cat: Codable, JSONEncodable, Hashable, Identifiable {

    public var id: String
    public var url: String?
    public var width: Double?
    public var height: Double?
    public var breeds: [Breeds]?

    public init(id: String = UUID().uuidString, url: String? = nil, width: Double? = nil, height: Double? = nil, breeds: [Breeds]? = nil) {
        self.id = id
        self.url = url
        self.width = width
        self.height = height
        self.breeds = breeds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case url
        case width
        case height
        case breeds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(breeds, forKey: .breeds)
    }
}

