//
// StoreImages.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StoreImages: Codable, JSONEncodable, Hashable {

    public var banner: String
    public var logo: String
    public var icon: String

    public init(banner: String, logo: String, icon: String) {
        self.banner = banner
        self.logo = logo
        self.icon = icon
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case banner
        case logo
        case icon
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(banner, forKey: .banner)
        try container.encode(logo, forKey: .logo)
        try container.encode(icon, forKey: .icon)
    }
}

