//
// Weight.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Weight: Codable, JSONEncodable, Hashable {

    public var imperial: String
    public var metric: String

    public init(imperial: String, metric: String) {
        self.imperial = imperial
        self.metric = metric
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imperial
        case metric
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(imperial, forKey: .imperial)
        try container.encode(metric, forKey: .metric)
    }
}

